#!/usr/bin/env node
/*
 * Writes src/content/filter.css from the selector lists in src/shared/rules.js.
 *
 * This is a developer tool, not a build step: the generated file is committed,
 * and you load the extension folder as it is. Run `npm run gen` after you
 * change a rule. `npm test` fails when the file is out of date.
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const rules = require('../src/shared/rules.js');

const OUT = path.join(__dirname, '..', 'src', 'content', 'filter.css');

function build() {
  const head = [
    '/*',
    ' * nospopo — generated by tools/gen-css.js. Do not edit by hand.',
    ' * Run `npm run gen` after a change in src/shared/rules.js.',
    ' *',
    ' * Every rule hangs off ' + rules.GATE + '. The filter therefore works',
    ' * before any script runs, and it stays on when a storage read is slow.',
    ' */',
    ''
  ].join('\n');

  const hide = rules.allSelectors().join(',\n') + ' {\n  display: none !important;\n}\n';

  const scripted = [
    '',
    '/* Items the script marks: shortcut tiles, shelf headers, empty shelves. */',
    rules.GATE + ' [data-nospopo-hide] {',
    '  display: none !important;',
    '}',
    ''
  ].join('\n');

  return head + hide + scripted;
}

if (require.main === module) {
  fs.writeFileSync(OUT, build());
  console.log('wrote ' + path.relative(process.cwd(), OUT));
}

module.exports = { build, OUT };
